server:
  port: 8024
  servlet.context-path: /soulmate
spring:
  application:
    name: soulmate
  thymeleaf:
    cache: false
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/soulmatefree?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: baishuzi
      password: dd0212pp0214
      initial-size: 3
      min-idle: 3
      max-active: 3
      max-wait: 3
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  activemq:
    broker-url: tcp://192.168.0.6:61616
    user: admin
    password: admin
    consumers: false
    producers: false
    jms:
      pub-sub-domain: false

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

swagger :
  user :
    title : 用户信息接口
    description : user
    group-name : user
    path-filter: /user
  message:
    title: 消息接口
    description: soulmate消息接口
    group-name: message（消息）
    path-filter: /message

log:
  path: G:\\code\\logs
  level: debug

